version: "2"
services:
  collectd:
    build: .
    depends_on:
      - influxdb
      - grafana
  influxdb:
    image: tutum/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826"
    environment:
      ADMIN_USER: "root"
      INFLUXDB_INIT_PWD: "somepassword"
      PRE_CREATE_DB: "collectd"
      COLLECTD_DB: "collectd"
      COLLECTD_BINDING: ":25826"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      INFLUXDB_URL: "http://influxdb:8086"
      INFLUXDB_NAME: "collectd"
      INFLUXDB_DATA_USER: "root"
      INFLUXDB_DATA_PW: "somepassword"
